name: room_alert_env
channels:
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - opencv-python==4.11.0.86
      - pyserial==3.5
